version: "3.3"
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: newspaper_delivery
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

    ports:
      - 6033:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root--execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  newspaper-delivery-system:
    image: newspaper-delivery-system:latest
    restart: on-failure
    build: ./
    expose:
      - "80"
    ports:
      - 80:80
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
