name: Github Actions CI

on: 
  push:
    branches: 
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions/cache@v1.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Setup MySQL
        run: mysql -uroot -p'root' -e 'CREATE DATABASE newspaper_delivery;'
        
      - name: Build Project
        run: ./mvnw clean install -B
        
      - name: Slack Notification
        uses: adityastic/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
