name: Github Actions CI

on:
  push:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions/cache@v1.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -p'root' -e 'CREATE DATABASE newspaper_delivery;'

      - name: Check Code Format
        run: ./mvnw spotless:check

      - name: Build Project
        run: ./mvnw -B clean package

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Docker Build and Deploy on Packages
        run: ./.github/scripts/docker-build-branch.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        uses: adityastic/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Push Coverage Report
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#      - name: Upload JAR
#        run: ./.github/scripts/upload-jar.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
