name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Setup MySQL
        run: mysql -u root -p 'root' -e 'CREATE DATABASE newspaper_delivery;'
        
      - name: Build Project
        run: ./mvnw clean install -B
