name: Github Actions CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions/cache@v1.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set Tag Version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Docker Build
        run: ./.github/scripts/docker-build.sh
        env:
          REL_VER: ${{ env.RELEASE_VERSION }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
